In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

Following thru this guide: https://www.learnpytorch.io/

# Fundamentals

In [2]:
import torch
torch.__version__

'2.5.1+cu124'

In [3]:
# scalar
scalar = torch.tensor(8) # zero-dim tensor
scalar, scalar.ndim, scalar.item()

(tensor(8), 0, 8)

In [4]:
# vector
vector = torch.tensor([6,7]) # single-dim
vector, vector.ndim, vector.shape # length 2 single dim

(tensor([6, 7]), 1, torch.Size([2]))

In [5]:
# matrix
mat = torch.tensor([[7,8], 
                   [9,10]])
mat, mat.shape # each entry is dim, value is length
# 2 dim of length 2 (2x2)

(tensor([[ 7,  8],
         [ 9, 10]]),
 torch.Size([2, 2]))

In [6]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR, TENSOR.shape, TENSOR.ndim # should be 1X3X3 and ndim = 3
# go outer to inner dim
# first 0th, then 1st, then 2nd dim

(tensor([[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]),
 torch.Size([1, 3, 3]),
 3)

In [7]:
# random tensors
rand_tensor = torch.rand(size=(224, 224, 3))
rand_tensor, rand_tensor.dtype

(tensor([[[0.3436, 0.7191, 0.0174],
          [0.8965, 0.2683, 0.9044],
          [0.8400, 0.4995, 0.1378],
          ...,
          [0.2684, 0.1794, 0.2461],
          [0.0717, 0.3140, 0.8801],
          [0.9285, 0.3631, 0.6309]],
 
         [[0.8512, 0.8267, 0.2644],
          [0.1670, 0.0671, 0.6812],
          [0.8438, 0.8090, 0.4157],
          ...,
          [0.2793, 0.8674, 0.6264],
          [0.6694, 0.0476, 0.5807],
          [0.2936, 0.6651, 0.9293]],
 
         [[0.7571, 0.9280, 0.8795],
          [0.9001, 0.5637, 0.0643],
          [0.8360, 0.6837, 0.9548],
          ...,
          [0.8061, 0.0516, 0.1386],
          [0.1697, 0.9661, 0.5771],
          [0.3736, 0.3120, 0.3304]],
 
         ...,
 
         [[0.6129, 0.1147, 0.4369],
          [0.6032, 0.2415, 0.3781],
          [0.9685, 0.9397, 0.2354],
          ...,
          [0.5666, 0.3347, 0.0334],
          [0.6190, 0.4313, 0.3596],
          [0.1599, 0.7461, 0.7633]],
 
         [[0.8378, 0.2666, 0.7763],
          [0

In [8]:
zeros = torch.zeros(size=(2,2))
ones = torch.ones(size=(2,2))
zeros, ones

(tensor([[0., 0.],
         [0., 0.]]),
 tensor([[1., 1.],
         [1., 1.]]))

In [9]:
zero_to_ten = torch.arange(0,12, step=2)
zero_to_ten

tensor([ 0,  2,  4,  6,  8, 10])

In [10]:
ten_ones = torch.ones_like(input=zero_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1])

In [11]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [12]:
float_16_tensor = torch.tensor([3,2,6], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

## Tensor Ops

In [13]:
rand = torch.rand(size=(1,5))
rand, rand + 5

(tensor([[0.3532, 0.3359, 0.3331, 0.7126, 0.3079]]),
 tensor([[5.3532, 5.3359, 5.3331, 5.7126, 5.3079]]))

In [14]:
ones = torch.ones(size=(2,2))
ones, ones * 2

(tensor([[1., 1.],
         [1., 1.]]),
 tensor([[2., 2.],
         [2., 2.]]))

In [15]:
zeros = torch.zeros_like(input=ones)
zeros, zeros - 10

(tensor([[0., 0.],
         [0., 0.]]),
 tensor([[-10., -10.],
         [-10., -10.]]))

In [16]:
ones * (zeros + 2)

tensor([[2., 2.],
        [2., 2.]])

In [17]:
# matrix mult.
# inner dims must match
# (3, 2) @ (3, 2) won't work
# (2, 3) @ (3, 2) will work

# output will have outer dims as new dims
# (2, 3) @ (3, 2) -> (2, 2)

tensor = torch.tensor([1,2,3])
tensor.shape, tensor.ndim

(torch.Size([3]), 1)

In [18]:
# element wise vs matrix mult.
# matrix mult. adds together at end
tensor * tensor, tensor @ tensor, tensor.matmul(tensor) # (3) and (3) match

(tensor([1, 4, 9]), tensor(14), tensor(14))

In [19]:
%%time
tensor @ tensor

CPU times: user 204 µs, sys: 44 µs, total: 248 µs
Wall time: 207 µs


tensor(14)

In [20]:
%%time
tensor.matmul(tensor) # faster

CPU times: user 0 ns, sys: 775 µs, total: 775 µs
Wall time: 655 µs


tensor(14)

In [21]:
A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

A, B.T, A.shape, torch.transpose(B, 0, 1).shape # transpose switches dims.

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 tensor([[ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([3, 2]),
 torch.Size([2, 3]))

In [22]:
torch.mm(A, B.T) # matrix mult.

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [23]:
# Linear layer
# m x n => m input features to n output neurons

torch.manual_seed(42)

linear = torch.nn.Linear(in_features=3, out_features=6)

x = A.T # 2x3 (2 inputs of size 3)
output = linear(x)

print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")
# output = 2x3 @ 3x6 => 2x6 (2 outputs with 6 features)

Input shape: torch.Size([2, 3])

Output:
tensor([[0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
        [1.7186, 1.4009, 3.5818, 1.7408, 2.6017, 2.5123]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([2, 6])


In [24]:
# aggregation

x = torch.arange(0, 100, 10)
x.min(), x.max(), x.type(torch.float32).mean(), x.sum() # scalars

(tensor(0), tensor(90), tensor(45.), tensor(450))

In [25]:
x.argmax(), x.argmin() # positional min/max

(tensor(9), tensor(0))

In [26]:
# reshaping, stacking, squeezing, unsqueezing

x = torch.arange(1, 8)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7]), torch.Size([7]))

In [27]:
x_reshaped = x.reshape(1, 7) # added extra dimension
x_reshaped, x_reshaped.shape # creates new copy without sharing data (copy)

(tensor([[1, 2, 3, 4, 5, 6, 7]]), torch.Size([1, 7]))

In [28]:
z = x.view(1, 7)
z, z.shape # view reshapes but shares data (reference)

(tensor([[1, 2, 3, 4, 5, 6, 7]]), torch.Size([1, 7]))

In [29]:
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7]]), tensor([5, 2, 3, 4, 5, 6, 7]))

In [30]:
x_stacked = torch.stack([x,x,x], dim=1) # zero concats; 1 concats element wise
x_stacked

tensor([[5, 5, 5],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7]])

In [31]:
print(x_reshaped, x_reshaped.shape)

x_squeezed = x_reshaped.squeeze()
print(x_squeezed, x_squeezed.shape) # squeeze to a single dimension
x_reshaped = x_squeezed.unsqueeze(dim=1) # add 1 at certain dimension
print(x_reshaped, x_reshaped.shape)


tensor([[5, 2, 3, 4, 5, 6, 7]]) torch.Size([1, 7])
tensor([5, 2, 3, 4, 5, 6, 7]) torch.Size([7])
tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7]]) torch.Size([7, 1])


In [32]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1) # returns view
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [33]:
# indexing

x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [34]:
x[:, 0] # all values in 0th dim and 0 index in 1st dim

tensor([[1, 2, 3]])

In [35]:
x[:, :, 1] # all values in 0th and 1st but get 2nd index

tensor([[2, 5, 8]])

In [36]:
!nvidia-smi
torch.cuda.is_available()

/bin/bash: line 1: nvidia-smi: command not found


False

In [37]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

In [38]:
torch.backends.mps.is_available()

False

## Review

- scalar, tensor, etc. (0th, 1st, 2nd dims)
- shape, ndim, dtype, device (tensor info)
- matmul (matrix mult)
- count the brackets on one side for dims + count items for length
- view, reshape (reshaping tensors)
- squeeze, unsqueeze (all dims of size 1 removed or add 1 dim of size 1)
- nn.Linear - rows = weights for one neuron
- (mxn weight matrix => m inputs and n outputs)
- ones, zeroes
- rand
- arange
- stack (on dim)
- transpose, permute (to change dim order)

# Workflow Fundamentals